[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/docs"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
ENVIRONMENT = "production"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"
ALGORITHM = "HS256"
SECRET_KEY = "${{RAILWAY_SERVICE_APP_BOLETO_SECRET_KEY}}"
PORT = "8000" 