[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
healthcheckInterval = 15
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
ENVIRONMENT = "production"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"
ALGORITHM = "HS256"
SECRET_KEY = "${{RAILWAY_SERVICE_APP_BOLETO_SECRET_KEY}}"
PORT = "8000" 